### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by DomWilliams0**
Fixes some small typos and whitespace errors found browsing the site. Hope it helps!

### CODE REVIEW

**Comment by pavpd** [comment]
when

**Comment by itsbapic** [comment]
You beat me to it, was busy with my own similar commit hahaha. Well done! Looks clean

**Review by ssertay — APPROVED** [review]

**Comment by windatang** [comment]
thx, we will pick a diff do code review

**Comment by windatang** [comment]
https://github.com/Loopring/loopring-web-v2/pull/264

**Pull request closed without merging**
